#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ -d $OPENSHIFT_DATA_DIR/cassandra ]
then
	exit 0
else
	cd $OPENSHIFT_DATA_DIR
	curl -OL http://downloads.datastax.com/community/dsc.tar.gz
	tar -xzvf dsc.tar.gz
	rm *.tar.gz
	mv dsc-cassandra-* cassandra
	mkdir cassandra-data
	cd cassandra-data
	mkdir data
	mkdir saved_caches
	mkdir commitlog
	touch system.log
	cd ../cassandra/conf/
	sed -ig 's,/var/lib/cassandra,$HOME/app-root/data/cassandra-data,' cassandra.yaml
	sed -ig 's/127.0.0.1/'$OPENSHIFT_INTERNAL_IP'/g' cassandra.yaml
	sed -ig 's/localhost/'$OPENSHIFT_INTERNAL_IP'/g' cassandra.yaml	
	sed -ig 's,7000,17000,' cassandra.yaml	
	sed -ig 's,7001,17001,' cassandra.yaml
	sed -ig 's,9160,19160,' cassandra.yaml
	sed -ig 's/localhost/'$OPENSHIFT_INTERNAL_IP'/g' cassandra.yaml	
	sed -ig 's,/var/log/cassandra,$HOME/app-root/data/cassandra-data,' log4j-server.properties
	sed -ig 's,${max_sensible_yg_in_mb}M,256M,' cassandra-env.sh
	sed -ig 's,${desired_yg_in_mb}M,256M,' cassandra-env.sh
	sed -ig '/jmxremote/s/^/#/' cassandra-env.sh
fi
