#!/bin/bash
# The logic to stop your application should be put in this script.
kill $(ps aux | grep 'cassandra' | awk '{print $2}')
kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
